# app/schemas/brew_log.py
from pydantic import BaseModel
from typing import Optional
from datetime import datetime


class BrewLogBase(BaseModel):
    recipe_id: Optional[int] = None
    bean_id: Optional[int] = None
    machine_id: Optional[str] = None
    brew_id: str  # Unique ID generated by the machine
    notes: Optional[str] = None


class BrewLogCreate(BrewLogBase):
    """Used when creating a brew log right after brewing finishes"""
    recipe_id: int  # Required at creation time
    machine_id: str
    brew_id: str


class BrewLogResponse(BrewLogBase):
    """Response model - what client receives"""
    log_id: int
    user_id: str
    recipe_id: Optional[int]
    child_recipe_id: Optional[int]  # The new modified recipe generated from review
    brewed_at: datetime

    # Review feedback fields (filled after user submits review)
    review_taste: Optional[int] = None        # 1-7
    review_tds: Optional[int] = None          # 1-7
    review_weight: Optional[int] = None       # 1-7 (brew ratio perception)
    review_intensity: Optional[int] = None    # 1-7
    review_notes: Optional[str] = None

    class Config:
        from_attributes = True  # Allows mapping from SQLAlchemy model


class BrewLogWithReviewUpdate(BaseModel):
    """Internal or partial update model - used if you need to update review fields separately"""
    review_taste: Optional[int] = None
    review_tds: Optional[int] = None
    review_weight: Optional[int] = None
    review_intensity: Optional[int] = None
    review_notes: Optional[str] = None
    child_recipe_id: Optional[int] = None